[workspace]
resolver = "2"
members = ["linker", "loader", "vsbf"]

[workspace.dependencies]
bitflags = { version = "2.6.0", features = ["bytemuck"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
capstone = "0.12.0"
libc = "0.2.158"
nom = "7.1.3"
