[package]
name = "vsbf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "linker"
[[bin]]
name = "loader"

[dependencies]
bitflags = { version = "2.6.0", features = ["bytemuck"] }
capstone = "0.12.0"
libc = "0.2.158"
nom = "7.1.3"
